import { enrichSectionsWithTopicDetails } from '../../../lib/topicDetails'

const reactSectionsSource = [
  {
    category: 'React - Core Concepts',
    color: 'var(--color-react)',
    tag: 'react',
    topics: [
      { name: 'JSX', desc: 'Syntax, expressions, fragments, self-closing' },
      { name: 'Components (Functional)', desc: 'Arrow functions, props, default props' },
      { name: 'Props & PropTypes', desc: 'Passing data down, prop validation' },
      { name: 'State (useState)', desc: 'Local state, updater function, immutability' },
      { name: 'useEffect', desc: 'Side effects, deps array, cleanup function' },
      { name: 'useRef', desc: 'DOM refs, persisting values without re-render' },
      { name: 'useContext', desc: 'Context API, createContext, Provider, Consumer' },
      { name: 'useReducer', desc: 'Complex state, action/dispatch pattern' },
      { name: 'useMemo & useCallback', desc: 'Memoization, referential equality' },
      { name: 'Custom Hooks', desc: 'Extracting reusable stateful logic' },
    ],
  },
  {
    category: 'React - Patterns & Ecosystem',
    color: 'var(--color-react)',
    tag: 'react',
    topics: [
      { name: 'React Router v6', desc: 'BrowserRouter, Routes, NavLink, Outlet, loaders' },
      { name: 'State Management (Redux Toolkit)', desc: 'createSlice, thunk, RTK Query' },
      { name: 'Zustand', desc: 'Lightweight global state with hooks' },
      { name: 'React Query / TanStack Query', desc: 'Server state, caching, mutations, invalidation' },
      { name: 'Forms (React Hook Form)', desc: 'register, handleSubmit, errors, Zod schema' },
      { name: 'Component Composition', desc: 'children prop, compound components, slots' },
      { name: 'Controlled vs Uncontrolled', desc: 'Inputs with state vs defaultValue/ref' },
      { name: 'Error Boundaries', desc: 'Class component catch, ErrorBoundary pattern' },
      { name: 'Suspense & Lazy Loading', desc: 'React.lazy, Suspense fallback, code splitting' },
      { name: 'Portals', desc: 'Rendering outside parent DOM (modals, tooltips)' },
      { name: 'Reconciliation & Virtual DOM', desc: 'Diffing algorithm, key prop importance' },
      { name: 'React.memo', desc: 'Skipping re-renders for pure components' },
      { name: 'Lifting State Up', desc: 'Sharing state via common ancestor' },
      { name: 'Higher-Order Components', desc: 'HOC pattern, wrapping components' },
      { name: 'Render Props', desc: 'Sharing code via prop-as-function' },
    ],
  },
  {
    category: 'React - Styling, Testing & Performance',
    color: 'var(--color-react)',
    tag: 'react',
    topics: [
      { name: 'Tailwind CSS with React', desc: 'Utility classes, cn(), variants, dark mode' },
      { name: 'Styled Components / Emotion', desc: 'CSS-in-JS, theming, dynamic styles' },
      { name: 'CSS Modules', desc: 'Scoped styles, :local, composes' },
      { name: 'Accessibility (a11y)', desc: 'ARIA roles, keyboard nav, semantic HTML' },
      { name: 'Testing with React Testing Library', desc: 'render, userEvent, queries, act' },
      { name: 'Vitest / Jest Setup', desc: 'jsdom, setup files, coverage' },
      { name: 'Storybook Basics', desc: 'Component docs, stories, controls, actions' },
      { name: 'Performance Profiler', desc: 'React DevTools, flame chart, wasted renders' },
      { name: 'useTransition & useDeferredValue', desc: 'Concurrent features, non-urgent updates' },
      { name: 'React 19 / New APIs', desc: 'use(), Actions, optimistic UI, cache()' },
      { name: 'Micro-frontend Concepts', desc: 'Module federation, independent deploys' },
      { name: 'TypeScript with React', desc: 'Props types, generics, event types, FC<>' },
      { name: 'Vite Build Tool', desc: 'HMR, config, plugins, env vars' },
      { name: 'PWA with React', desc: 'Service workers, manifest, Workbox' },
      { name: 'Internationalisation (i18n)', desc: 'react-i18next, locale routing, plurals' },
      { name: 'Animations (Framer Motion)', desc: 'motion, variants, AnimatePresence, layout' },
      { name: 'Drag & Drop (dnd-kit)', desc: 'Sortable, sensors, collision detection' },
      { name: 'Real-time UI with Socket.io', desc: 'Client hook, reconnect, rooms' },
      { name: 'Data Visualisation (Recharts)', desc: 'LineChart, BarChart, ResponsiveContainer' },
      { name: 'Infinite Scroll & Virtualisation', desc: 'react-virtual, IntersectionObserver' },
    ],
  },
]

export const reactSections = enrichSectionsWithTopicDetails(reactSectionsSource)
