import { enrichSectionsWithTopicDetails } from '../../../lib/topicDetails'

const generalSectionsSource = [
  {
    category: 'General CS & DevOps Essentials',
    color: 'var(--color-general)',
    tag: 'general',
    topics: [
      { name: 'HTTP/HTTPS & Status Codes', desc: '1xx-5xx, headers, methods, HTTPS handshake' },
      { name: 'REST vs GraphQL vs gRPC', desc: 'Trade-offs, when to use each' },
      { name: 'SQL Fundamentals', desc: 'SELECT, JOIN, GROUP BY, indexes, EXPLAIN' },
      { name: 'NoSQL Concepts', desc: 'Document, Key-Value, CAP theorem basics' },
      { name: 'Database Indexing', desc: 'B-tree, composite index, query optimization' },
      { name: 'ACID Transactions', desc: 'Atomicity, Consistency, Isolation, Durability' },
      { name: 'Git & GitHub', desc: 'branching, rebase, cherry-pick, PR workflow' },
      { name: 'Docker Basics', desc: 'Image, container, Dockerfile, compose' },
      { name: 'CI/CD Concepts', desc: 'GitHub Actions, pipelines, deploy stages' },
      { name: 'Linux CLI Essentials', desc: 'grep, sed, awk, chmod, cron, top' },
      { name: 'DNS & Domain Routing', desc: 'A record, CNAME, TTL, CDN basics' },
      { name: 'JWT vs Session Auth', desc: 'Stateless vs stateful, trade-offs' },
      { name: 'OAuth 2.0 & OpenID Connect', desc: 'Authorization flows, PKCE, tokens' },
      { name: 'API Security Basics', desc: 'XSS, CSRF, SQL injection, OWASP Top 10' },
      { name: 'Caching Strategies', desc: 'Cache-aside, write-through, eviction policies' },
      { name: 'Pub/Sub & Message Queues', desc: 'RabbitMQ, Redis pub/sub, event-driven' },
      { name: 'WebSockets vs SSE', desc: 'Full-duplex vs one-way server push' },
      { name: 'Load Balancing Basics', desc: 'Round-robin, sticky sessions, health checks' },
      { name: 'Big O Notation', desc: 'Time & space complexity, common algorithms' },
      { name: 'Data Structures', desc: 'Array, linked list, hash map, tree, graph' },
      { name: 'Design Patterns', desc: 'Singleton, Observer, Factory, Strategy, Adapter' },
      { name: 'SOLID Principles', desc: 'SRP, OCP, LSP, ISP, DIP - with examples' },
      { name: 'Clean Code Practices', desc: 'Naming, functions, comments, DRY, KISS' },
      { name: 'Testing Types', desc: 'Unit, integration, e2e, TDD vs BDD' },
      { name: 'Agile & Scrum Basics', desc: 'Sprints, standups, backlog, velocity' },
      { name: 'System Design Intro', desc: 'Scalability, DB sharding, horizontal scaling' },
      { name: 'Nginx Basics', desc: 'Reverse proxy, SSL termination, config' },
      { name: 'Cloud Fundamentals (AWS/GCP)', desc: 'EC2, S3, RDS, Lambda - overview' },
      { name: 'TypeScript Fundamentals', desc: 'Types, interfaces, generics, utility types' },
      { name: 'Monorepo Tools (Turborepo/NX)', desc: 'Shared packages, build caching' },
      { name: 'Semantic Versioning (semver)', desc: 'major.minor.patch, range syntax' },
      { name: 'Web Performance (Core Web Vitals)', desc: 'LCP, FID, CLS, Lighthouse' },
      { name: 'Browser Dev Tools', desc: 'Network tab, performance, console, Sources' },
      { name: 'Regex Fundamentals', desc: 'Patterns, groups, lookahead - for validation' },
      { name: 'Soft Skills for Interviews', desc: 'STAR method, explaining decisions, asking questions' },
    ],
  },
]

export const generalSections = enrichSectionsWithTopicDetails(generalSectionsSource)
