import { enrichSectionsWithTopicDetails } from '../../../lib/topicDetails'

const nodeSectionsSource = [
  {
    category: 'Node.js - Core & Runtime',
    color: 'var(--color-node)',
    tag: 'node',
    topics: [
      { name: 'Event Loop', desc: 'Call stack, microtasks, macrotasks, phases' },
      { name: 'Non-blocking I/O', desc: 'Why Node is fast for I/O-bound tasks' },
      { name: 'Modules (CommonJS & ESM)', desc: 'require(), import/export, module scope' },
      { name: 'Buffer & Streams', desc: 'Readable, Writable, Transform streams, piping' },
      { name: 'File System (fs module)', desc: 'readFile, writeFile, watch, streams' },
      { name: 'HTTP Module', desc: 'Creating raw HTTP servers without frameworks' },
      { name: 'Path & OS Modules', desc: 'Cross-platform path handling, OS info' },
      { name: 'Process & Env', desc: 'process.env, process.argv, signals, exit codes' },
      { name: 'EventEmitter', desc: 'Custom events, on/emit pattern' },
      { name: 'Child Processes', desc: 'spawn, exec, fork - multi-processing' },
    ],
  },
  {
    category: 'Node.js - Express & APIs',
    color: 'var(--color-node)',
    tag: 'node',
    topics: [
      { name: 'Express.js Basics', desc: 'app.get/post, req/res, listen' },
      { name: 'Express Middleware', desc: 'app.use(), order matters, error MW' },
      { name: 'Router & Route Groups', desc: 'express.Router(), modular routing' },
      { name: 'REST API Design', desc: 'HTTP verbs, status codes, resource naming' },
      { name: 'Request Validation', desc: 'express-validator, Joi, Zod' },
      { name: 'JWT Authentication', desc: 'jsonwebtoken, sign, verify, refresh tokens' },
      { name: 'Cookie & Session', desc: 'cookie-parser, express-session, secure flags' },
      { name: 'CORS in Node', desc: 'cors package, origin whitelist, credentials' },
      { name: 'Error Handling Middleware', desc: '4-arg middleware, centralized error handling' },
      { name: 'Rate Limiting (express-rate-limit)', desc: 'DDoS protection, sliding window' },
      { name: 'File Uploads (Multer)', desc: 'Disk/memory storage, file validation' },
      { name: 'Environment Config (dotenv)', desc: '.env, config validation, environments' },
    ],
  },
  {
    category: 'Node.js - DB, Performance & Advanced',
    color: 'var(--color-node)',
    tag: 'node',
    topics: [
      { name: 'MongoDB with Mongoose', desc: 'Schema, model, CRUD, virtuals, populate' },
      { name: 'SQL with Sequelize/Knex', desc: 'ORM vs query builder, migrations' },
      { name: 'Redis in Node', desc: 'ioredis, caching, pub/sub, rate limiting' },
      { name: 'Async/Await & Promises', desc: 'Error handling, Promise.all, race' },
      { name: 'Clustering', desc: 'cluster module, PM2 cluster mode' },
      { name: 'Worker Threads', desc: 'CPU-bound tasks, thread communication' },
      { name: 'WebSockets (Socket.io)', desc: 'Real-time bidirectional communication' },
      { name: 'Node Security Basics', desc: 'Helmet.js, injection, prototype pollution' },
      { name: 'Testing with Jest/Mocha', desc: 'Unit tests, supertest for API testing' },
      { name: 'Logging (Winston/Morgan)', desc: 'Structured logs, levels, transports' },
      { name: 'GraphQL with Node', desc: 'Apollo Server, typeDefs, resolvers' },
      { name: 'Microservices Intro', desc: 'Service separation, REST vs message queues' },
      { name: 'Bull/BullMQ Queues', desc: 'Background jobs, concurrency, retries' },
      { name: 'Docker with Node', desc: 'Dockerfile, .dockerignore, compose' },
      { name: 'PM2 Process Manager', desc: 'Daemon, restart policy, cluster mode' },
      { name: 'Serverless Node (Lambda)', desc: 'Handler functions, cold starts, events' },
      { name: 'OpenAPI / Swagger Docs', desc: 'swagger-jsdoc, swagger-ui-express' },
      { name: 'Node.js Performance Profiling', desc: 'clinic.js, --inspect, flame graphs' },
    ],
  },
]

export const nodeSections = enrichSectionsWithTopicDetails(nodeSectionsSource)
