export const laravelSections = [
  {
    category: 'Laravel - Core Fundamentals',
    color: 'var(--color-laravel)',
    tag: 'laravel',
    level: 'fundamentals',
    topics: [
      { name: 'MVC Architecture', desc: 'Model-View-Controller pattern in Laravel' },
      { name: 'Routing Basics', desc: 'web.php, api.php, route params & naming' },
      { name: 'Middleware', desc: 'Request filtering, auth middleware, custom MW' },
      { name: 'Service Container', desc: 'IoC container, binding & dependency injection' },
      { name: 'Service Providers', desc: 'Bootstrapping & registering services' },
      { name: 'Facades', desc: 'Static proxy to services in the container' },
      { name: 'Blade Templating', desc: 'Directives, layouts, components, slots' },
      { name: 'Eloquent ORM', desc: 'ActiveRecord pattern, models, relationships' },
      { name: 'Migrations', desc: 'Schema versioning, up/down methods' },
      { name: 'Seeders & Factories', desc: 'Fake data generation with Faker' },
    ],
  },
  {
    category: 'Laravel - Database & Eloquent',
    color: 'var(--color-laravel)',
    tag: 'laravel',
    level: 'intermediate',
    topics: [
      { name: 'Query Builder', desc: 'DB::table(), select, where, join, raw queries' },
      { name: 'Eloquent Relationships', desc: 'hasOne, hasMany, belongsTo, M2M, polymorphic' },
      { name: 'Eager vs Lazy Loading', desc: 'N+1 problem, with(), load()' },
      { name: 'Accessors & Mutators', desc: 'Attribute casting and transformation' },
      { name: 'Scopes (Local & Global)', desc: 'Reusable query constraints' },
      { name: 'Soft Deletes', desc: 'trashed, restore, forceDelete' },
      { name: 'Pagination', desc: 'paginate(), simplePaginate(), cursor pagination' },
      { name: 'Database Transactions', desc: 'DB::transaction(), rollback on failure' },
      { name: 'Observers', desc: 'Model lifecycle event listeners' },
      { name: 'Collections', desc: 'Fluent array manipulation with Laravel Collections' },
    ],
  },
  {
    category: 'Laravel - Auth, API & Advanced',
    color: 'var(--color-laravel)',
    tag: 'laravel',
    level: 'advanced',
    topics: [
      { name: 'Authentication (Breeze/Jetstream)', desc: 'Session-based auth scaffolding' },
      { name: 'Sanctum', desc: 'SPA & mobile token-based authentication' },
      { name: 'Passport', desc: 'Full OAuth2 server implementation' },
      { name: 'Authorization (Gates & Policies)', desc: 'User permission logic' },
      { name: 'Form Requests & Validation', desc: 'Request classes, rules, custom messages' },
      { name: 'API Resources', desc: 'Transforming models to JSON responses' },
      { name: 'Queues & Jobs', desc: 'Async jobs, drivers (Redis, DB), failed jobs' },
      { name: 'Events & Listeners', desc: 'Observer pattern for decoupled code' },
      { name: 'Notifications', desc: 'Mail, SMS, Slack, DB notifications' },
      { name: 'Artisan Commands', desc: 'Custom CLI commands, tinker, make:*' },
      { name: 'Laravel Caching', desc: 'Redis, Memcached, cache tags, TTL' },
      { name: 'File Storage (Filesystem)', desc: 'Disks, S3, local, symbolic links' },
      { name: 'Testing in Laravel', desc: 'PHPUnit, Feature vs Unit tests, HTTP tests' },
      { name: 'Rate Limiting', desc: 'throttle middleware, custom rate limiters' },
      { name: 'CORS in Laravel', desc: 'config/cors.php, fruitcake package' },
      { name: 'Scheduling (Task Scheduler)', desc: 'Cron-based task scheduling with schedule()' },
      { name: 'Laravel Horizon', desc: 'Queue monitoring dashboard (Redis)' },
      { name: 'Laravel Telescope', desc: 'Debug assistant & request inspector' },
      { name: 'Package Development Basics', desc: 'Creating reusable Laravel packages' },
      { name: 'Multi-tenancy Concepts', desc: 'DB per tenant vs shared DB strategies' },
      { name: 'Laravel Livewire Intro', desc: 'Full-stack reactive components in Blade' },
      { name: 'Repository Pattern', desc: 'Abstracting data layer from controllers' },
      { name: 'SOLID in Laravel', desc: 'Applying SOLID principles in PHP/Laravel' },
      { name: 'Config & .env Management', desc: 'Env vars, config caching, environments' },
      { name: 'Error Handling & Logging', desc: 'Handler, Monolog, Log channels, Sentry' },
    ],
  },
]

export const laravelSectionsByLevel = {
  fundamentals: laravelSections.find((section) => section.level === 'fundamentals'),
  intermediate: laravelSections.find((section) => section.level === 'intermediate'),
  advanced: laravelSections.find((section) => section.level === 'advanced'),
}
