import { enrichSectionsWithTopicDetails } from '../../../lib/topicDetails'

const nextSectionsSource = [
  {
    category: 'Next.js - Routing & Rendering',
    color: '#bbb',
    tag: 'next',
    topics: [
      { name: 'Pages vs App Router', desc: 'pages/ directory vs app/ directory (Next 13+)' },
      { name: 'File-based Routing', desc: 'Dynamic routes [id], catch-all [...slug]' },
      { name: 'Server Components', desc: 'Default async components, no client state' },
      { name: "Client Components ('use client')", desc: 'useState, useEffect, interactivity' },
      { name: 'SSR (getServerSideProps)', desc: 'Server-side rendering per request' },
      { name: 'SSG (getStaticProps)', desc: 'Static generation at build time' },
      { name: 'ISR (Incremental Static Regen)', desc: 'revalidate, on-demand revalidation' },
      { name: 'Layouts & Templates', desc: 'layout.tsx, template.tsx, nesting' },
      { name: 'Loading & Error UI', desc: 'loading.tsx, error.tsx, Suspense' },
      { name: 'Route Groups', desc: '(group) folders - layout without URL segment' },
    ],
  },
  {
    category: 'Next.js - Data, API & Deployment',
    color: '#bbb',
    tag: 'next',
    topics: [
      { name: 'API Routes', desc: 'pages/api or app/api route.ts handlers' },
      { name: 'Server Actions', desc: "'use server', form actions, mutations" },
      { name: 'Fetch & Caching', desc: 'fetch() with cache, no-store, revalidate' },
      { name: 'next/image', desc: 'Optimized images, lazy load, priority' },
      { name: 'next/font', desc: 'Google/local fonts, zero layout shift' },
      { name: 'next/link & next/navigation', desc: 'Client nav, useRouter, usePathname' },
      { name: 'Middleware (middleware.ts)', desc: 'Edge middleware, auth redirects' },
      { name: 'Environment Variables', desc: 'NEXT_PUBLIC_, server vs client vars' },
      { name: 'Metadata API', desc: 'generateMetadata, title templates, OG images' },
      { name: 'NextAuth.js / Auth.js', desc: 'OAuth, credentials, session management' },
      { name: 'Prisma with Next.js', desc: 'Type-safe ORM, schema, migrations' },
      { name: 'Next.js + Tailwind CSS', desc: 'Setup, purge, responsive utilities' },
      { name: 'Vercel Deployment', desc: 'Push to deploy, preview URLs, analytics' },
      { name: 'Edge Runtime vs Node Runtime', desc: 'Performance trade-offs, API support' },
      { name: 'Parallel & Intercepting Routes', desc: 'Advanced routing patterns in App Router' },
      { name: 'Static Params', desc: 'generateStaticParams for dynamic SSG routes' },
      { name: 'Draft Mode', desc: 'Preview unpublished CMS content in development or staging' },
      { name: 'Route Handlers', desc: 'app/api with Request and Response helpers' },
      { name: 'Cookies & Headers APIs', desc: 'Read request metadata in server components and handlers' },
      { name: 'Cache Tags & Revalidation', desc: 'revalidateTag, revalidatePath, fine-grained cache control' },
      { name: 'Streaming with Suspense', desc: 'Progressive rendering and partial UI delivery' },
      { name: 'next/script', desc: 'Third-party script loading strategies and optimization' },
      { name: 'Bundle Analysis', desc: 'Inspect client/server bundle size and reduce bloat' },
      { name: 'SEO in Next.js', desc: 'Metadata, canonical URLs, structured data, sitemap' },
      { name: 'CMS Integration', desc: 'Fetching content from headless CMS platforms like Sanity or Contentful' },
    ],
  },
]

export const nextSections = enrichSectionsWithTopicDetails(nextSectionsSource)
